### PR TITLE
service : use ng2-translate getBrowserLanguage to fix browser languag…

### LINKED ISSUE #13: Browser language detection doesn't work
On chrome, with French as main language, default language returned by LocalizeParser._getBrowserLanguage is not fr.

### PR DESCRIPTION
**Pull request by bellolau**
…e detection.
resolve #13

### CODE REVIEW

**Comment by meeroslav** [comment]
Hi,
I would just replace this with call to `getBrowserLanguage` in `ng2-translate` or copy entire method here.

You've missed one important thing though, we need to make sure that browser's language is indeed in our list of defined locales:

```ts
if (this.locales.indexOf(lang) !== -1) {
  return lang;
}
```
Something like this would work:
```ts
let lang = this.translate.getBrowserLang();
if (lang && this.locales.indexOf(lang) !== -1) {
  return lang;
}
return null;
```

Please modify your code and I'll include it in the master. Thanks for the effort

**Comment by samvloeberghs** [comment]
you might need to refactor this if you use ng2-translate to get the browser language when you'll be supporting universal. I would suggest to use your own way to determine the browserlanguage, or you create extra dependencies.

**Comment by meeroslav** [comment]
@samvloeberghs Code has three levels of determining language (in order of priority):
* Path (yourwebsite/lang)
* Browser (only used if `window.navigator` is defined which is not the case in `universal` scenario)
* First language in `locales` array

In case of server-side rendering you should point your crawler to specific local sub-url (yourwebsite/lang) in the website. I haven't tried in out myself yet, so it might not be as simple as I expect.

**Comment by samvloeberghs** [comment]
@meeroslav good point! In my routersetup I do something like this for the main route in my main node module:

`{ path: '', redirectTo: '/en', pathMatch: 'full' }, `

If would include zone and do something like this, I might be able to redirect to the correct language on the serverside:

```
function getRequestLanguage() {
  return Zone.current.get('req')['requested_language'] || 'en' ;
}
...
`{ path: '', redirectTo: '/'+getRequestLanguage(), pathMatch: 'full' }, `
```

**Comment by meeroslav** [comment]
Implemented in the project due to unresponsiveness of OP

**Pull request closed without merging**
