### PR TITLE
Updated for Angular 6

### PR DESCRIPTION
**Pull request by brandonkelton**
I updated this code to work with Angular 6 and the newer version of rxjs.  Node changes are significant, but there weren't very many code changes.  I had to move a few things around, like tests and change the tests a bit.  I also created some mocks to keep in line with true "unit" testing, as some of the tests were testing units outside themselves, and it was easier to write a mock for those other units.  Let me know if you find this useful.

### CODE REVIEW

**Comment by elmarbeckmann** [comment]
Great PR, does anybody have contact with guys like @manzonif or @meeroslav? Who can check/merge this request? @brandonkelton were you in touch with them or have you heard anything?

**Comment by brandonkelton** [comment]
I was never in touch with anyone.  Just saw a need and went for it.  I was going to use it after I finished, but realized it would not work for my situation.  Thought I’d post the code and make a merge request.

-Brandon Kelton

________________________________

**Comment by Heleboel** [comment]
It seems that building this locally does not work due to missing files (src/tsconfig.app.ts and src/main.ts to name a few). Or is 'npm run build' the wrong command to build this?

**Comment by meeroslav** [comment]
@brandonkelton, unfortunately, due to my long absence, there were several PRs for upgrading to Angular 6 and I have decided to merge in the first one proposed.

I appreciate your help and support and I warmly welcome you to continue doing so in the future.

Thanks again!

**Pull request closed without merging**
