### PR TITLE
ng9 support

### PR DESCRIPTION
**Pull request by deerua**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

ng9 support

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

now it support angular 9 and Ivy

## Does this PR introduce a breaking change?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by arangelp** [comment]
@deerua :  Does this merge give the compatibility to the localize router for allowing working with ng9?
I am trying to do this for quite a long time.

**Comment by mehmetatacan** [comment]
> @deerua : Does this merge give the compatibility to the localize router for allowing working with ng9?
> I am trying to do this for quite a long time

i have same problem. Did you check that is it resolved

**Comment by arangelp** [comment]
Tomorrow i will try it. This is my major blocker to ng9.
i cross fingers :)

**Comment by deerua** [comment]
@arangelp @mehmetatacan works fine in our big project 
i'll add some changes - but it for testing

**Comment by mehmetatacan** [comment]
> @arangelp @mehmetatacan works fine in our big project
> i'll add some changes - but it for testing

Thanks for reply, I will try as soon as possible

**Comment by Ismaestro** [comment]
Please!!! Check this PR we need for our project! Thanks in advance!

**Pull request closed without merging**
