### PR TITLE
Angular 6 version

### PR DESCRIPTION
**Pull request by gilsdav**
I only changed the source code here.
I didn't tried in this configuration because I used the "generate lib" feature of @angular/cli to simplify the working process.
Work's well with all manual tests I did on the CLI configuration.

### CODE REVIEW

**Comment by gilsdav** [comment]
I only changed the source code here.
I didn't tried in this configuration because I used the "generate lib" feature of @angular/cli to simplify the working process.
Work's well with all manual tests I did on the CLI configuration.

**Comment by gilsdav** [comment]
I haven't seen the other PR but if it can help to make localize-router more stable on Angular 6.
Issues that correct for me:

- Url doesn't change on lang change
- The lang only change on first "changeLang" call and, after that, only every 2 calls.

**Comment by YaroslavLyzlov** [comment]
please, merge this request ))

**Comment by gilsdav** [comment]
@YaroslavLyzlov You can use this https://www.npmjs.com/package/@gilsdav/ngx-translate-router deployment until it is merged if you don't need the http-loader. I didn't fork it for now.

**Comment by meeroslav** [comment]
Hi @gilsdav, unfortunately, due to my long absence, there were several PRs for upgrading to Angular 6 and I have decided to merge in the first one proposed.

I did, however, look into your branch and 'stole' a few ideas. Hope you don't mind.
Please keep up the good work and thank you for all the support.

Thanks again!

**Pull request closed without merging**
